In [48]:
import pandas as pd
import numpy as np
import json
from pandas.io.json import json_normalize

In [ ]:
with open(r'D:\work\votes\ВАО.txt', 'r') as f:
    text = json.loads(f.read().replace('\n', ' '))['items']
    #print(text[1]['districts']['candidates']['1'][1])
    #for i in text:
    #    for j in i.keys():
    #        for k in i[j].keys():
    #            print(j,k)
    #print(text[0].keys())
    #print('\ndistricts')
    #print(text[0]['districts'].keys())
    #print(text[0]['districts']['candidates'].keys())
    #print(text[0]['districts']['candidates']['1'][0].keys())
    #print(text[0]['districts']['stats'].keys())
    #print(text[0]['districts']['stats']['1'].keys())
    #print('\nregion')
    #print(text[0]['region'].keys())
    #print(text[0]['region']['human_name'])
    #print(text[0]['region']['region_name'])
    #print('\nuiks')
    #print(text[0]['uiks'].keys())
    #print(text[0]['uiks']['859'].keys())
    #print(text[0]['uiks']['859']['district'])
    #print(text[1]['uiks'].keys())
    #print('\n\n\n')

In [113]:
with open(r'D:\work\votes\ЮАО.txt', 'r') as f:
    text = json.loads(f.read().replace('\n', ' '))['items']
    regions = []
    uiks= []
    parties = []
    candidates = []
    candidates_names = []
    for region in text:
        #print(region['region']['region_name'], '\n\n')
        region_name = region['region']['region_name']
        for i in region['districts']['candidates'].keys():
            regions.append({'region_name':region_name, 'district':i, "data":region['districts']['candidates'][i]})
        for j in region['uiks']:
            uiks.append({'region_name':region_name,'uik':j, 'votes':region['uiks'][j]['votes']})
            parties += region['uiks'][j]['votes'].keys()
            candidates.append({'region_name':region_name,'uik':j, 'votes':region['uiks'][j]['candidates']})
            candidates_names += region['uiks'][j]['candidates'].keys()
        #for uik in region['districts']['candidates'].keys():
        #    for candidate in region['districts']['candidates'][uik]:
        #        print(uik, candidate['full_name'], candidate['votes'], '\n')
#print(regions[1])
print(uiks[1])
parties = set(parties)
data_regions = json_normalize(regions, 'data', 'region_name')
print(data_regions.head())
data_uiks = json_normalize(uiks)
#data_uiks_melt = pd.melt(data_uiks, id_vars=['region_name', 'uik'], value_vars=['votes.'+i for i in parties]).dropna()
data_uiks_melt = pd.melt(data_uiks.rename(columns=lambda x: x.split('.')[-1]), id_vars=['region_name', 'uik'], value_vars=parties).dropna()
print(parties)
print(data_uiks.head())
print(data_uiks_melt.head())

{'region_name': 'Бирюлево Восточное', 'uik': '1656', 'votes': {'Коммунисты России': 78, 'ЛДПР': 58, 'КПРФ': 111, 'Самовыдвижение': 35, 'Яблоко': 80, 'Единая Россия': 425, 'Справедливая Россия': 15, 'Родина': 10}}
  advancewith_final  district                     full_name  id  is_ext  \
0     Единая Россия         1     Яковлева Елена Николаевна  -1   False
1     Единая Россия         1         Кузина Марина Юрьевна  -1   False
2     Единая Россия         1    Нерсесова Елена Валериевна  -1   False
3     Единая Россия         1     Молчанов Павел Викторович  -1   False
4     Единая Россия         1  Зайнетдинов Марат Валерьевич  -1   False

   is_our                              name  votes         region_name
0   False     [Яковлева, Елена, Николаевна]   1233  Бирюлево Восточное
1   False         [Кузина, Марина, Юрьевна]   1212  Бирюлево Восточное
2   False    [Нерсесова, Елена, Валериевна]   1157  Бирюлево Восточное
3   False     [Молчанов, Павел, Викторович]   1154  Бирюлево Восточное
4   False  [Зайнетдинов, Марат, Валерьевич]   1093  Бирюлево Восточное
{'ЛДПР', 'Партия Великое Отечество', 'Партия Роста', 'Родина', 'Справедливая Россия', 'ПАРНАС', 'Народ против коррупции', 'Коммунисты России', 'КПРФ', 'Яблоко', 'Единая Россия', 'Партия пенсионеров', 'Партия возрождения села', 'Самовыдвижение'}
          region_name   uik  votes.Единая Россия  votes.КПРФ  \
0  Бирюлево Восточное  1655                  244         202
1  Бирюлево Восточное  1656                  425         111
2  Бирюлево Восточное  1657                  397         132
3  Бирюлево Восточное  1658                  545         129
4  Бирюлево Восточное  1662                  401         135

   votes.Коммунисты России  votes.ЛДПР  votes.Народ против коррупции  \
0                     66.0        34.0                           NaN
1                     78.0        58.0                           NaN
2                    121.0        53.0                           NaN
3                     74.0        41.0                           NaN
4                     85.0        45.0                           NaN

   votes.ПАРНАС  votes.Партия Великое Отечество  votes.Партия Роста  \
0           NaN                             NaN                 NaN
1           NaN                             NaN                 NaN
2           NaN                             NaN                 NaN
3           NaN                             NaN                 NaN
4           NaN                             NaN                 NaN

   votes.Партия возрождения села  votes.Партия пенсионеров  votes.Родина  \
0                            NaN                       NaN          10.0
1                            NaN                       NaN          10.0
2                            NaN                       NaN           8.0
3                            NaN                       NaN           6.0
4                            NaN                       NaN          11.0

   votes.Самовыдвижение  votes.Справедливая Россия  votes.Яблоко
0                  55.0                       69.0          96.0
1                  35.0                       15.0          80.0
2                  54.0                        7.0          84.0
3                  46.0                       12.0          50.0
4                  55.0                       12.0          93.0
          region_name   uik variable  value
0  Бирюлево Восточное  1655     ЛДПР   34.0
1  Бирюлево Восточное  1656     ЛДПР   58.0
2  Бирюлево Восточное  1657     ЛДПР   53.0
3  Бирюлево Восточное  1658     ЛДПР   41.0
4  Бирюлево Восточное  1662     ЛДПР   45.0

In [109]:
data_candidates = json_normalize(candidates)

In [115]:
data_candidates_melt = pd.melt(data_candidates.rename(columns=lambda x: x.split('.')[-1]), id_vars=['region_name', 'uik'], value_vars=candidates_names).dropna()

In [119]:
data_candidates_melt[data_candidates_melt.uik == '1863'].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 520 entries, 2047377 to 2704865
Data columns (total 4 columns):
region_name    520 non-null object
uik            520 non-null object
variable       520 non-null object
value          520 non-null object
dtypes: object(4)
memory usage: 20.3+ KB

In [107]:
data_uiks[data_uiks.uik == '1863']

,region_name,uik,votes.Единая Россия,votes.КПРФ,votes.Коммунисты России,votes.ЛДПР,votes.Народ против коррупции,votes.ПАРНАС,votes.Партия Великое Отечество,votes.Партия Роста,votes.Партия возрождения села,votes.Партия пенсионеров,votes.Родина,votes.Самовыдвижение,votes.Справедливая Россия,votes.Яблоко
209,Нагатинский затон,1863,655,100,35.0,25.0,NaN,NaN,NaN,23.0,NaN,NaN,NaN,87.0,22.0,134.0

In [42]:
zaton = data_uiks_melt[data_uiks_melt['region_name'] == 'Нагатинский затон']

In [106]:
zaton[zaton.uik == '1863']

            region_name   uik             variable  value
209   Нагатинский затон  1863                 ЛДПР   25.0
1137  Нагатинский затон  1863         Партия Роста   23.0
2065  Нагатинский затон  1863  Справедливая Россия   22.0
3457  Нагатинский затон  1863    Коммунисты России   35.0
3921  Нагатинский затон  1863                 КПРФ  100.0
4385  Нагатинский затон  1863               Яблоко  134.0
4849  Нагатинский затон  1863        Единая Россия  655.0
6241  Нагатинский затон  1863       Самовыдвижение   87.0

In [96]:
percent_zaton = (zaton.groupby(['uik', 'variable'])['value'].sum().groupby(level = 0)).transform(lambda x: x/x.sum())
sum_zaton = zaton.groupby(['uik'])['value'].sum()
sum_zaton = pd.DataFrame(sum_zaton).reset_index()
sum_zaton = sum_zaton.rename(columns={'value':'sum'})
percent_zaton = pd.DataFrame(group_zaton).reset_index()
percent_zaton = percent_zaton.rename(columns={'value':'percent'})
#group_zaton[group_zaton['variable'] == 'Единая Россия']
new_zaton = percent_zaton[percent_zaton['variable'] == 'Единая Россия']
new_zaton = percent_zaton[percent_zaton['variable'] == 'Единая Россия'][['uik', 'percent']].merge(sum_zaton[['uik','sum']], left_on='uik', right_on='uik', how='inner')
new_zaton[['uik']] = new_zaton[['uik']].apply(pd.to_numeric)
new_zaton.sort_values('percent', ascending=False)

     uik   percent     sum
27  1890  0.642540  1575.0
0   1863  0.605920  1081.0
24  1887  0.588957  1467.0
14  1877  0.584493  1006.0
1   1864  0.567082   723.0
12  1875  0.532759   580.0
18  1881  0.529889   987.0
23  1886  0.529228   958.0
21  1884  0.528155  1030.0
3   1866  0.523675  1415.0
13  1876  0.511864   885.0
22  1885  0.487020   963.0
2   1865  0.483871   155.0
17  1880  0.479784  1113.0
19  1882  0.455464  1089.0
10  1873  0.453423  1782.0
7   1870  0.452249  1267.0
11  1874  0.448737   673.0
15  1878  0.444072   894.0
20  1883  0.443243  1110.0
28  1891  0.436893   824.0
5   1868  0.435720  1299.0
25  1888  0.435673  1026.0
4   1867  0.425887   479.0
26  1889  0.415174   949.0
9   1872  0.412083  1109.0
8   1871  0.396607   943.0
16  1879  0.391595  1047.0
6   1869  0.387874  1369.0
32  1895  0.387303  1717.0
29  1892  0.372589   985.0
30  1893  0.366357   969.0
31  1894  0.320236   509.0

In [65]:
import geopandas as gpd

In [66]:
uik_geo = pd.read_csv(r'C:\Users\avzhukov\Downloads\77\77.csv')

In [67]:
uik_geo.head()

,id,lat,lon,number_official,address_voting,place_voting,comment,is_applied,geocoding_precision,tik,tik_id,region
0,573,55.896735,37.595735,574,"ул. Лескова, д. 8а",ГБОУ СОШ №254 с/п №1,NaN,True,building,ТИК района Бибирево,2631,Москва
1,574,55.896428,37.595564,575,"ул. Лескова, д. 8а",ГБОУ СОШ №254 с/п №1,NaN,True,building,ТИК района Бибирево,2631,Москва
2,1467,55.643766,37.718843,1470,"Батайский пр., д. 21",Школа 1141,NaN,True,building,ТИК района Марьино,2665,Москва
3,1468,55.643534,37.719272,1471,"Батайский пр., д. 21",Школа 1141,NaN,True,building,ТИК района Марьино,2665,Москва
4,1469,55.643581,37.720930,1472,"Батайский пр., д. 23",Школа 499,NaN,True,building,ТИК района Марьино,2665,Москва

In [97]:
my_zaton = new_zaton.merge(uik_geo[['address_voting', 'number_official', 'lat', 'lon', 'place_voting']], left_on='uik', right_on='number_official', how='inner')

In [98]:
my_zaton.head()

,uik,percent,sum,address_voting,number_official,lat,lon,place_voting
0,1863,0.605920,1081.0,"Андропова пр-т, д. 17, корп. 5",1863,55.682236,37.669351,Гимназия № 1527
1,1864,0.567082,723.0,"Андропова пр-т, д. 17, корп. 5",1864,55.682572,37.668466,Гимназия № 1527
2,1865,0.483871,155.0,"Кленовый бульв., д. 7, корп. 2",1865,55.683754,37.676545,Частная школа «Самсон»
3,1866,0.523675,1415.0,"Андропова пр-т, д. 17, корп. 3",1866,55.682088,37.667946,Гимназия № 1527
4,1867,0.425887,479.0,"Андропова пр-т, д. 17, корп. 3",1867,55.682076,37.668584,Гимназия № 1527

In [99]:
from shapely.geometry import Polygon, Point

In [100]:
my_zaton['geometry'] = my_zaton.apply(lambda z: Point(z.lon, z.lat), axis=1)

In [101]:
my_zaton_gdf = gpd.GeoDataFrame(my_zaton)

In [102]:
my_zaton_gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Int64Index: 33 entries, 0 to 32
Data columns (total 9 columns):
uik                33 non-null int64
percent            33 non-null float64
sum                33 non-null float64
address_voting     33 non-null object
number_official    33 non-null int64
lat                33 non-null float64
lon                33 non-null float64
place_voting       33 non-null object
geometry           33 non-null object
dtypes: float64(4), int64(2), object(3)
memory usage: 2.6+ KB

In [103]:
my_zaton_gdf.to_file(r"D:\work\data\zaton.shp", encoding = 'utf-8')